In [8]:
#Numpyの基本的な関数や使い方についてまとめています
#備忘録的なものです
import numpy as np

In [2]:
#-四則演算-

In [5]:
a = 1
b = 2
#足し算
print(a + b)
#引き算
print(a - b)
#掛け算
print(a * b)
#指数(a^b)
print(a ** b)
#割り算
print(a / b)
#割り算(整数部分のみ)
print(a // b)
#割り算(余り部分のみ)
print(a % b)

3
-1
2
1
0.5
0
1


In [6]:
#-配列(Array)の作成-

In [7]:
#リストの配列変換

In [10]:
List = [1, 2, 3]
array = np.array(List)
print(array)

[1 2 3]


In [11]:
#多次元配列の作成

In [17]:
#リストから作成
List1 = [1, 2, 3]
List2 = [4, 5, 6]
array1 = np.array([List1, List2])
print(array1)
#arange関数で作成
array2 = np.arange(1,7).reshape(2,3)
print(array2)

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]


In [18]:
#要素が全て0の配列・多次元配列を作成

In [21]:
#1次元
List1 = np.zeros(10)
print(List1)
#2次元
List2 = np.zeros((2,5))
print(List2)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [22]:
#要素が全て1の配列・多次元配列を作成

In [23]:
#1次元
List1 = np.ones(10)
print(List1)
#2次元
List2 = np.ones((2,5))
print(List2)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [24]:
#単位行列を作成

In [25]:
array = np.eye(5)
print(array)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [26]:
#連続した数値の配列を作成

In [28]:
#0～9まで
array1 = np.arange(10)
print(array1)
#5～9まで
array2 = np.arange(5,10)
print(array2)
#0～100まで20間隔で
array3 = np.arange(0,101,10)
print(array3)

[0 1 2 3 4 5 6 7 8 9]
[5 6 7 8 9]
[  0  10  20  30  40  50  60  70  80  90 100]


In [29]:
#-配列情報の取得

In [30]:
#配列のデータ型を取得

In [32]:
array = np.array([1,2,3])
print(array.dtype)

int32


In [33]:
#配列のサイズを取得

In [34]:
array = np.array([1,2,3])
print(array.shape)

(3,)


In [35]:
#配列の次元数を取得

In [36]:
array = np.array([1,2,3])
print(array.ndim)

1


In [37]:
#配列の要素数を取得

In [38]:
array = np.array([1,2,3])
print(array.size)

3


In [39]:
#-インデックス操作

In [40]:
#インデックスを指定して配列から値を抽出

In [41]:
array = np.arange(1,10)
print(array)
#5を取得(5のインデックスは4)
print(array[4])
#8を取得(8のインデックスは7)
print(array[7])

[1 2 3 4 5 6 7 8 9]
5
8


In [42]:
#インデックスを指定して行列から行を取得

In [43]:
array = np.arange(9).reshape(3,3)
print(array)
#1行目を取得
print(array[0])
#3行目を取得
print(array[2])

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[0 1 2]
[6 7 8]


In [44]:
#インデックスを指定して行列から列を取得

In [45]:
array = np.arange(9).reshape(3,3)
print(array)
#2列目を取得
print(array[:,1])

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[1 4 7]


In [46]:
#インデックスを指定して行列から値を取得

In [47]:
array = np.arange(9).reshape(3,3)
print(array)
#2行目2列目の値を取得
print(array[1,1])

[[0 1 2]
 [3 4 5]
 [6 7 8]]
4


In [48]:
#インデックスを指定して配列から特定範囲の値を抽出

In [50]:
array = np.arange(1,10)
print(array)
#3～5を取得
print(array[2:5])

[1 2 3 4 5 6 7 8 9]
[3 4 5]


In [51]:
#インデックスを指定して配列中の値を更新

In [52]:
array = np.arange(1,10)
print(array)
#5を100に更新
array[4] = 100
print(array)

[1 2 3 4 5 6 7 8 9]
[  1   2   3   4 100   6   7   8   9]


In [53]:
#演算関数

In [54]:
a1 = np.arange(9).reshape(3,3)
a2 = np.arange(9,18).reshape(3,3)
print(a1)
print(a2)
#加法
print(np.add(a1,a2))

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[ 9 11 13]
 [15 17 19]
 [21 23 25]]


In [56]:
a1 = np.arange(9).reshape(3,3)
a2 = np.arange(9,18).reshape(3,3)
print(a1)
print(a2)
#減法
print(np.subtract(a1,a2))

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[-9 -9 -9]
 [-9 -9 -9]
 [-9 -9 -9]]


In [57]:
a1 = np.arange(9).reshape(3,3)
a2 = np.arange(9,18).reshape(3,3)
print(a1)
print(a2)
#乗法
print(np.multiply(a1,a2))

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[  0  10  22]
 [ 36  52  70]
 [ 90 112 136]]


In [58]:
a1 = np.arange(9).reshape(3,3)
a2 = np.arange(9,18).reshape(3,3)
print(a1)
print(a2)
#除法
print(np.divide(a1,a2))

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[0.         0.1        0.18181818]
 [0.25       0.30769231 0.35714286]
 [0.4        0.4375     0.47058824]]


In [59]:
a1 = np.arange(9).reshape(3,3)
a2 = np.arange(9,18).reshape(3,3)
print(a1)
print(a2)
#べき乗
print(np.power(a1,a2))

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[          0           1        2048]
 [     531441    67108864  1808548329]
 [ 2033549312 -1526366847           0]]


In [69]:
a1 = np.arange(9).reshape(3,3)
a2 = np.arange(9,18).reshape(3,3)
print(a1)
print(a2)
#行列積
print(np.dot(a1,a2))

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[ 42  45  48]
 [150 162 174]
 [258 279 300]]


In [60]:
a1 = np.arange(9).reshape(3,3)
print(a1)
#平方根
print(np.sqrt(a1))

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0.         1.         1.41421356]
 [1.73205081 2.         2.23606798]
 [2.44948974 2.64575131 2.82842712]]


In [61]:
a1 = np.arange(9).reshape(3,3)
print(a1)
#絶対値
print(np.abs(a1))

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [62]:
a1 = np.arange(9).reshape(3,3)
print(a1)
#平方
print(np.square(a1))

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 0  1  4]
 [ 9 16 25]
 [36 49 64]]


In [64]:
a1 = np.arange(1,10).reshape(3,3)
print(a1)
#自然対数
print(np.log(a1))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[0.         0.69314718 1.09861229]
 [1.38629436 1.60943791 1.79175947]
 [1.94591015 2.07944154 2.19722458]]


In [65]:
a1 = np.arange(1,10).reshape(3,3)
print(a1)
#2底対数
print(np.log2(a1))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[0.         1.         1.5849625 ]
 [2.         2.32192809 2.5849625 ]
 [2.80735492 3.         3.169925  ]]


In [66]:
a1 = np.arange(1,10).reshape(3,3)
print(a1)
#10底対数
print(np.log10(a1))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[0.         0.30103    0.47712125]
 [0.60205999 0.69897    0.77815125]
 [0.84509804 0.90308999 0.95424251]]


In [67]:
a1 = np.arange(1,10).reshape(3,3)
print(a1)
#指数関数
print(np.exp(a1))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02]
 [1.09663316e+03 2.98095799e+03 8.10308393e+03]]


In [70]:
a1 = np.arange(1,10).reshape(3,3)
print(a1)
#平均値
print(np.average(a1))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
5.0


In [71]:
a1 = np.arange(1,10).reshape(3,3)
print(a1)
#分散
print(np.var(a1))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
6.666666666666667


In [72]:
a1 = np.arange(1,10).reshape(3,3)
print(a1)
#標準偏差
print(np.std(a1))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
2.581988897471611


In [73]:
a1 = np.arange(1,10).reshape(3,3)
print(a1)
#総和
print(np.sum(a1))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
45


In [74]:
#-行列操作-

In [76]:
#行列転置
a1 = np.arange(1,10).reshape(3,3)
print(a1)
#.T
print(a1.T)
#transpose()
print(a1.transpose())

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [77]:
#多次元化

In [78]:
a1 = np.arange(25)
print(a1)
print(a1.reshape(5,5))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
